[project]
name = "ai-agent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "google-genai==1.12.1",
    "pandas>=3.0.0",
    "pandas-stubs~=3.0.0",
    "python-dotenv==1.1.0",
    "scikit-learn>=1.8.0",
]
